[package]
name = "advent-of-code"
version = "0.0.1"
edition = "2021"
publish = false
authors = ["Daniel Oakman"]
# default-run = "advent_of_code"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pico-args = "0.5.0"
